### ISSUE TITLE
Suggestion : Adding SonarScanner for Gradle Plugin

### ISSUE THREAD

**Issue by ramshty** [arygm/QuickFix#31]
**Suggestion : Adding SonarScanner for Gradle Plugin**

the current CI setup ensures that the SonarCloud analysis runs automatically upon pushes, I think it’s crucial to also provide developers with the ability to run local SonarCloud analysis. This allows them to check for code smells, bugs, and other issues before pushing their code, reducing the likelihood of CI pipeline failures and helping maintain a cleaner commit history.

By integrating the SonarScanner for Gradle plugin, developers can trigger local SonarCloud analysis with a simple Gradle command (./gradlew sonarqube). This can be a valuable tool for ensuring code quality even before commits are made.

For a step-by-step guide to install the plugin, you can refer to the official documentation here: [SonarScanner for Gradle Setup](https://docs.sonarsource.com/sonarcloud/advanced-setup/ci-based-analysis/sonarscanner-for-gradle/).

_Originally posted by @ramshty in https://github.com/arygm/QuickFix/pull/23#pullrequestreview-2350481287_

**Comment by JitterKiller** [comment]
Look at the end of the `CI.yaml ` file. You can run Sonar locally using `gradle build sonar`, results will be shown [here](https://sonarcloud.io/project/overview?id=arygm_QuickFix) :)
