### ISSUE TITLE
Firebase Set Up

### ISSUE THREAD

**Issue by Sebbayra** [arygm/QuickFix#38]
When trying to sign in with google or email and password, i get this message:

com.google.firebase.FirebaseException: An internal error has occurred. [ Requests from this Android client application com.arygm.quickfix are blocked. ]

I am 99% sure that my code is fine.

**Comment by JitterKiller** [comment]
Make sure to have `google-sercices.json` on your local repo directory as well as the right SHA-1 key added on Firebase (the debug variant). 

The PR linked to this issue should resolve the issue (I've added `default_web_client_id` string value on the app)

**Comment by Sebbayra** [comment]
> Make sure to have `google-sercices.json` on your local repo directory as well as the right SHA-1 key added on Firebase (the debug variant).
> 
> The PR linked to this issue should resolve the issue (I've added `default_web_client_id` string value on the app)

These are stuff i already added when testing my code, these aren't the fix unfortunately, our firebase requests are getting blocked for some reason, i'll push my code later tonight for you to test.

**Comment by JitterKiller** [comment]
Firebase is now working perfectly (removed restriction of API key), this PR doesn't need to be merged as changes on this branch will be added to profile_repository branch. See #49
